version: '3'

services:

### MySQL Container #########################################
  
  mysql:
    image: mysql:8.0
    container_name: larablog-mysql
    volumes:
      - ./dockers/mysql:/var/lib/mysql
    # env_file: .env
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_ROOT_PASSWORD: 'password'
### Workspace Utilities Container ###########################

  nginx:
    image: nginx
    container_name: larablog-nginx
    working_dir: /var/www
    ports:
      - "80:80"
      - "443:443"
    # env_file: .env
    volumes:
      - ./:/var/www
      - ./dockers/nginx/vhost.conf:/etc/nginx/conf.d/default.conf

  php:
    image : hichamajarif/lara-php7.4-fpm
    container_name: larablog-php
    working_dir: /var/www/
    # env_file: .env
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor

    privileged: true
    ports:
      - "9000:9000"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: larablog-phpmyadmin
    links:
      - mysql:db
    restart: always
    ports:
      - 8081:80
    volumes:
      - /sessions